/*
 @licstart  The following is the entire license notice for the JavaScript code in this file.

 The MIT License (MIT)

 Copyright (C) 1997-2020 by Dimitri van Heesch

 Permission is hereby granted, free of charge, to any person obtaining a copy of this software
 and associated documentation files (the "Software"), to deal in the Software without restriction,
 including without limitation the rights to use, copy, modify, merge, publish, distribute,
 sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:

 The above copyright notice and this permission notice shall be included in all copies or
 substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING
 BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
 DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

 @licend  The above is the entire license notice for the JavaScript code in this file
*/
var menudata={children:[
{text:"Main Page",url:"index.html"},
{text:"Related Pages",url:"pages.html"},
{text:"Namespaces",url:"namespaces.html",children:[
{text:"Namespace List",url:"namespaces.html"},
{text:"Namespace Members",url:"namespacemembers.html",children:[
{text:"All",url:"namespacemembers.html",children:[
{text:"a",url:"namespacemembers.html#index_a"},
{text:"acro",url:"namespacemembers.html#index_a"},
{text:"acti",url:"namespacemembers.html#index_a"},
{text:"anno",url:"namespacemembers.html#index_a"},
{text:"appe",url:"namespacemembers.html#index_a"},
{text:"blen",url:"namespacemembers.html#index_b"},
{text:"c",url:"namespacemembers.html#index_c"},
{text:"colo",url:"namespacemembers.html#index_c"},
{text:"cont",url:"namespacemembers.html#index_c"},
{text:"data",url:"namespacemembers.html#index_d"},
{text:"dest",url:"namespacemembers.html#index_d"},
{text:"enco",url:"namespacemembers.html#index_e"},
{text:"encr",url:"namespacemembers.html#index_e"},
{text:"erro",url:"namespacemembers.html#index_e"},
{text:"f",url:"namespacemembers.html#index_f"},
{text:"fiel",url:"namespacemembers.html#index_f"},
{text:"filt",url:"namespacemembers.html#index_f"},
{text:"font",url:"namespacemembers.html#index_f"},
{text:"func",url:"namespacemembers.html#index_f"},
{text:"g",url:"namespacemembers.html#index_g"},
{text:"glyp",url:"namespacemembers.html#index_g"},
{text:"high",url:"namespacemembers.html#index_h"},
{text:"hori",url:"namespacemembers.html#index_h"},
{text:"iden",url:"namespacemembers.html#index_i"},
{text:"info",url:"namespacemembers.html#index_i"},
{text:"inli",url:"namespacemembers.html#index_i"},
{text:"keyl",url:"namespacemembers.html#index_k"},
{text:"l",url:"namespacemembers.html#index_l"},
{text:"line",url:"namespacemembers.html#index_l"},
{text:"logs",url:"namespacemembers.html#index_l"},
{text:"oper",url:"namespacemembers.html#index_o"},
{text:"outl",url:"namespacemembers.html#index_o"},
{text:"page",url:"namespacemembers.html#index_p"},
{text:"pain",url:"namespacemembers.html#index_p"},
{text:"perm",url:"namespacemembers.html#index_p"},
{text:"post",url:"namespacemembers.html#index_p"},
{text:"r",url:"namespacemembers.html#index_r"},
{text:"rend",url:"namespacemembers.html#index_r"},
{text:"s",url:"namespacemembers.html#index_s"},
{text:"stri",url:"namespacemembers.html#index_s"},
{text:"stro",url:"namespacemembers.html#index_s"},
{text:"t",url:"namespacemembers.html#index_t"},
{text:"text",url:"namespacemembers.html#index_t"},
{text:"tili",url:"namespacemembers.html#index_t"},
{text:"toun",url:"namespacemembers.html#index_t"},
{text:"vers",url:"namespacemembers.html#index_v"},
{text:"vert",url:"namespacemembers.html#index_v"},
{text:"writ",url:"namespacemembers.html#index_w"}]},
{text:"Functions",url:"namespacemembers_func.html"},
{text:"Variables",url:"namespacemembers_vars.html"},
{text:"Typedefs",url:"namespacemembers_type.html"},
{text:"Enumerations",url:"namespacemembers_enum.html",children:[
{text:"a",url:"namespacemembers_enum.html#index_a"},
{text:"acro",url:"namespacemembers_enum.html#index_a"},
{text:"acti",url:"namespacemembers_enum.html#index_a"},
{text:"anno",url:"namespacemembers_enum.html#index_a"},
{text:"appe",url:"namespacemembers_enum.html#index_a"},
{text:"blen",url:"namespacemembers_enum.html#index_b"},
{text:"colo",url:"namespacemembers_enum.html#index_c"},
{text:"cont",url:"namespacemembers_enum.html#index_c"},
{text:"data",url:"namespacemembers_enum.html#index_d"},
{text:"dest",url:"namespacemembers_enum.html#index_d"},
{text:"enco",url:"namespacemembers_enum.html#index_e"},
{text:"encr",url:"namespacemembers_enum.html#index_e"},
{text:"erro",url:"namespacemembers_enum.html#index_e"},
{text:"f",url:"namespacemembers_enum.html#index_f"},
{text:"fiel",url:"namespacemembers_enum.html#index_f"},
{text:"filt",url:"namespacemembers_enum.html#index_f"},
{text:"font",url:"namespacemembers_enum.html#index_f"},
{text:"func",url:"namespacemembers_enum.html#index_f"},
{text:"glyp",url:"namespacemembers_enum.html#index_g"},
{text:"high",url:"namespacemembers_enum.html#index_h"},
{text:"hori",url:"namespacemembers_enum.html#index_h"},
{text:"iden",url:"namespacemembers_enum.html#index_i"},
{text:"info",url:"namespacemembers_enum.html#index_i"},
{text:"keyl",url:"namespacemembers_enum.html#index_k"},
{text:"line",url:"namespacemembers_enum.html#index_l"},
{text:"logs",url:"namespacemembers_enum.html#index_l"},
{text:"oper",url:"namespacemembers_enum.html#index_o"},
{text:"outl",url:"namespacemembers_enum.html#index_o"},
{text:"page",url:"namespacemembers_enum.html#index_p"},
{text:"pain",url:"namespacemembers_enum.html#index_p"},
{text:"perm",url:"namespacemembers_enum.html#index_p"},
{text:"post",url:"namespacemembers_enum.html#index_p"},
{text:"rend",url:"namespacemembers_enum.html#index_r"},
{text:"stri",url:"namespacemembers_enum.html#index_s"},
{text:"stro",url:"namespacemembers_enum.html#index_s"},
{text:"t",url:"namespacemembers_enum.html#index_t"},
{text:"text",url:"namespacemembers_enum.html#index_t"},
{text:"tili",url:"namespacemembers_enum.html#index_t"},
{text:"vers",url:"namespacemembers_enum.html#index_v"},
{text:"vert",url:"namespacemembers_enum.html#index_v"},
{text:"writ",url:"namespacemembers_enum.html#index_w"}]}]}]},
{text:"Classes",url:"annotated.html",children:[
{text:"Class List",url:"annotated.html"},
{text:"Class Index",url:"classes.html"},
{text:"Class Hierarchy",url:"hierarchy.html"},
{text:"Class Members",url:"functions.html",children:[
{text:"All",url:"functions.html",children:[
{text:"a",url:"functions.html#index_a"},
{text:"acti",url:"functions_a.html#index_a"},
{text:"anno",url:"functions_a.html#index_a"},
{text:"arra",url:"functions_a.html#index_a"},
{text:"axia",url:"functions_a.html#index_a"},
{text:"b",url:"functions_b.html#index_b"},
{text:"c",url:"functions_c.html#index_c"},
{text:"char",url:"functions_c.html#index_c"},
{text:"cid",url:"functions_c.html#index_c"},
{text:"colo",url:"functions_c.html#index_c"},
{text:"d",url:"functions_d.html#index_d"},
{text:"data",url:"functions_d.html#index_d"},
{text:"date",url:"functions_d.html#index_d"},
{text:"dest",url:"functions_d.html#index_d"},
{text:"dict",url:"functions_d.html#index_d"},
{text:"diff",url:"functions_d.html#index_d"},
{text:"docu",url:"functions_d.html#index_d"},
{text:"e",url:"functions_e.html#index_e"},
{text:"elem",url:"functions_e.html#index_e"},
{text:"enco",url:"functions_e.html#index_e"},
{text:"erro",url:"functions_e.html#index_e"},
{text:"expo",url:"functions_e.html#index_e"},
{text:"extg",url:"functions_e.html#index_e"},
{text:"f",url:"functions_f.html#index_f"},
{text:"file",url:"functions_f.html#index_f"},
{text:"filt",url:"functions_f.html#index_f"},
{text:"font",url:"functions_f.html#index_f"},
{text:"func",url:"functions_f.html#index_f"},
{text:"g",url:"functions_g.html#index_g"},
{text:"h",url:"functions_h.html#index_h"},
{text:"i",url:"functions_i.html#index_i"},
{text:"iden",url:"functions_i.html#index_i"},
{text:"imag",url:"functions_i.html#index_i"},
{text:"imme",url:"functions_i.html#index_i"},
{text:"info",url:"functions_i.html#index_i"},
{text:"l",url:"functions_l.html#index_l"},
{text:"m",url:"functions_m.html#index_m"},
{text:"memd",url:"functions_m.html#index_m"},
{text:"n",url:"functions_n.html#index_n"},
{text:"name",url:"functions_n.html#index_n"},
{text:"o",url:"functions_o.html#index_o"},
{text:"obje",url:"functions_o.html#index_o"},
{text:"outl",url:"functions_o.html#index_o"},
{text:"p",url:"functions_p.html#index_p"},
{text:"page",url:"functions_p.html#index_p"},
{text:"pain",url:"functions_p.html#index_p"},
{text:"pars",url:"functions_p.html#index_p"},
{text:"q",url:"functions_q.html#index_q"},
{text:"r",url:"functions_r.html#index_r"},
{text:"radi",url:"functions_r.html#index_r"},
{text:"rect",url:"functions_r.html#index_r"},
{text:"refe",url:"functions_r.html#index_r"},
{text:"s",url:"functions_s.html#index_s"},
{text:"samp",url:"functions_s.html#index_s"},
{text:"shad",url:"functions_s.html#index_s"},
{text:"stit",url:"functions_s.html#index_s"},
{text:"stre",url:"functions_s.html#index_s"},
{text:"stri",url:"functions_s.html#index_s"},
{text:"t",url:"functions_t.html#index_t"},
{text:"text",url:"functions_t.html#index_t"},
{text:"tili",url:"functions_t.html#index_t"},
{text:"tria",url:"functions_t.html#index_t"},
{text:"v",url:"functions_v.html#index_v"},
{text:"vari",url:"functions_v.html#index_v"},
{text:"w",url:"functions_w.html#index_w"},
{text:"writ",url:"functions_w.html#index_w"},
{text:"xref",url:"functions_x.html#index_x"},
{text:"~",url:"functions_~.html#index__7E"}]},
{text:"Functions",url:"functions_func.html",children:[
{text:"a",url:"functions_func.html#index_a"},
{text:"acti",url:"functions_func_a.html#index_a"},
{text:"anno",url:"functions_func_a.html#index_a"},
{text:"arra",url:"functions_func_a.html#index_a"},
{text:"axia",url:"functions_func_a.html#index_a"},
{text:"b",url:"functions_func_b.html#index_b"},
{text:"c",url:"functions_func_c.html#index_c"},
{text:"char",url:"functions_func_c.html#index_c"},
{text:"cid",url:"functions_func_c.html#index_c"},
{text:"colo",url:"functions_func_c.html#index_c"},
{text:"d",url:"functions_func_d.html#index_d"},
{text:"data",url:"functions_func_d.html#index_d"},
{text:"date",url:"functions_func_d.html#index_d"},
{text:"dest",url:"functions_func_d.html#index_d"},
{text:"dict",url:"functions_func_d.html#index_d"},
{text:"diff",url:"functions_func_d.html#index_d"},
{text:"docu",url:"functions_func_d.html#index_d"},
{text:"e",url:"functions_func_e.html#index_e"},
{text:"elem",url:"functions_func_e.html#index_e"},
{text:"enco",url:"functions_func_e.html#index_e"},
{text:"erro",url:"functions_func_e.html#index_e"},
{text:"expo",url:"functions_func_e.html#index_e"},
{text:"extg",url:"functions_func_e.html#index_e"},
{text:"f",url:"functions_func_f.html#index_f"},
{text:"file",url:"functions_func_f.html#index_f"},
{text:"filt",url:"functions_func_f.html#index_f"},
{text:"font",url:"functions_func_f.html#index_f"},
{text:"func",url:"functions_func_f.html#index_f"},
{text:"g",url:"functions_func_g.html#index_g"},
{text:"h",url:"functions_func_h.html#index_h"},
{text:"i",url:"functions_func_i.html#index_i"},
{text:"iden",url:"functions_func_i.html#index_i"},
{text:"imag",url:"functions_func_i.html#index_i"},
{text:"imme",url:"functions_func_i.html#index_i"},
{text:"info",url:"functions_func_i.html#index_i"},
{text:"l",url:"functions_func_l.html#index_l"},
{text:"m",url:"functions_func_m.html#index_m"},
{text:"memd",url:"functions_func_m.html#index_m"},
{text:"n",url:"functions_func_n.html#index_n"},
{text:"name",url:"functions_func_n.html#index_n"},
{text:"o",url:"functions_func_o.html#index_o"},
{text:"obje",url:"functions_func_o.html#index_o"},
{text:"outl",url:"functions_func_o.html#index_o"},
{text:"p",url:"functions_func_p.html#index_p"},
{text:"page",url:"functions_func_p.html#index_p"},
{text:"pain",url:"functions_func_p.html#index_p"},
{text:"pars",url:"functions_func_p.html#index_p"},
{text:"q",url:"functions_func_q.html#index_q"},
{text:"r",url:"functions_func_r.html#index_r"},
{text:"radi",url:"functions_func_r.html#index_r"},
{text:"rect",url:"functions_func_r.html#index_r"},
{text:"refe",url:"functions_func_r.html#index_r"},
{text:"s",url:"functions_func_s.html#index_s"},
{text:"samp",url:"functions_func_s.html#index_s"},
{text:"shad",url:"functions_func_s.html#index_s"},
{text:"stit",url:"functions_func_s.html#index_s"},
{text:"stre",url:"functions_func_s.html#index_s"},
{text:"stri",url:"functions_func_s.html#index_s"},
{text:"t",url:"functions_func_t.html#index_t"},
{text:"text",url:"functions_func_t.html#index_t"},
{text:"tili",url:"functions_func_t.html#index_t"},
{text:"tria",url:"functions_func_t.html#index_t"},
{text:"v",url:"functions_func_v.html#index_v"},
{text:"vari",url:"functions_func_v.html#index_v"},
{text:"w",url:"functions_func_w.html#index_w"},
{text:"writ",url:"functions_func_w.html#index_w"},
{text:"xref",url:"functions_func_x.html#index_x"},
{text:"~",url:"functions_func_~.html#index__7E"}]},
{text:"Variables",url:"functions_vars.html"}]}]},
{text:"Files",url:"files.html",children:[
{text:"File List",url:"files.html"}]}]}
